const data = [
  {
    title: "Douglas with Grandma Lincoln",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-1.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Sisters giving approval to the 1st haircut",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-2.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "Me and Carolyn in my wagon",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-3.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Our family outside the Log Church",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-4.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Siblings",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-5.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "My preacher look",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-10.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title:
      "Grandma Siggelkow with Glen and Gloria,  Grandma Lincoln with me and my sisters",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-11.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Grandma Lincoln and me",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-12.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "My first dog, Spot",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-13.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Uncle Jack Blizzard baptizing me",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-13-1.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Thanksgiving Dinner with friends at Roundup",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-14.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title:
      "Christmas Dinner down on the farm with Grandpa and Grandma and Uncle Dave",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-16.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "With cousins, Kathy and Pat, in Williams Lake",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-17.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "With Uncle Ralph's family in Williams Lake",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-17-1.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "Grandma Lincoln and us",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-18.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Family photos with Grandma",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-19.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Reading 'Dick & Jane' to Leslie",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-20.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "A surprised Grandma Lincoln",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-21.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Dad's School bus gang",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-22.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "More family photos",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-23.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "Performing at Pembina Bible Camp",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-24.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Children's camp at Pembina",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-24-1.jpg",
    rotate: "rotate-left",
    chapter: 1,
  },
  {
    title: "Opening my Meccano set present Christmas 1954",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-26.jpg",
    rotate: "rotate-middle",
    chapter: 1,
  },
  {
    title: "Outside the Church Dad built in Jarvie",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/1-27.jpg",
    rotate: "rotate-right",
    chapter: 1,
  },
  {
    title: "Our home in High River",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-1.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Our backyard with my VW bug",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-2.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title: "This picture was taken shortly after we moved to High River",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-2-1.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "About 1959",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-3.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "After the bout with Rheumatic Fever",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-4.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title:
      "Barbie and Janice were the first foster children that stayed with us",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-5.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "Wayne, Bev, Chris & Bob the Mclean foster family",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-5-1.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "Christmas dinner with Dan and Danny Schneider",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-6.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Glen and I taking Sharon out to BC",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-6-1.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title:
      "The last Christmas we had with Mom, Danny, Darla, Wayne, Gary, Mom, Henrietta, Aunt Annie and me",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-7.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title: "Christmas 1965",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-7-1.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "Uncle Cliff Christmas 1965",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-7-2.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Uncle Max Christmas 1965",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-7-3.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title: "Pal",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-8.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "Teenage Cousins",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-8-1.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Grandma and Sharon",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-9.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Darla and Wayne's wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-10.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title: "Leaving the Church",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-11.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "The Wedding party",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-12.jpg",
    rotate: "rotate-right",
    chapter: 2,
  },
  {
    title: "Dad & Hilda's wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-15.jpg",
    rotate: "rotate-left",
    chapter: 2,
  },
  {
    title: "Dad & Hilda's wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/2-17.jpg",
    rotate: "rotate-middle",
    chapter: 2,
  },
  {
    title: "Eston Bible College 1967",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-6.jpg",
    rotate: "rotate-right",
    chapter: 3,
  },
  {
    title: "Eston Bible College",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-8.jpg",
    rotate: "rotate-middle",
    chapter: 3,
  },
  {
    title: "My graduating class 1969",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-15.jpg",
    rotate: "rotate-left",
    chapter: 3,
  },
  {
    title: "Sharon & Ron's Wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-16.jpg",
    rotate: "rotate-right",
    chapter: 3,
  },
  {
    title: "Children's workers Doug & Russ",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-17.jpg",
    rotate: "rotate-middle",
    chapter: 3,
  },
  {
    title: "Teen Time,  Wally & his boat",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/3-18.jpg",
    rotate: "rotate-left",
    chapter: 3,
  },
  {
    title: "Zion (Before)",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-6.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "Zion (After)",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-8.jpg",
    rotate: "rotate-middle",
    chapter: 4,
  },
  {
    title: "Wally",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-9.jpg",
    rotate: "rotate-left",
    chapter: 4,
  },
  {
    title: "After the Dedication of Dallas",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-9-1.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "Outside My House at the Zion Church",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-10.jpg",
    rotate: "rotate-middle",
    chapter: 4,
  },
  {
    title: "Picnic with Donna",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-11.jpg",
    rotate: "rotate-left",
    chapter: 4,
  },
  {
    title: "Donna",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-12.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "Sadie Hawkins day",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-12-1.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "Carolyn & Les's Wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-13.jpg",
    rotate: "rotate-middle",
    chapter: 4,
  },
  {
    title: "Our Wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-15.jpg",
    rotate: "rotate-left",
    chapter: 4,
  },
  {
    title: "Our Wedding",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-18.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "Donna's Family",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-20.jpg",
    rotate: "rotate-middle",
    chapter: 4,
  },
  {
    title: "Honeymoon",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-22.jpg",
    rotate: "rotate-left",
    chapter: 4,
  },
  {
    title: "Honeymoon",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/4-23.jpg",
    rotate: "rotate-right",
    chapter: 4,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-5.jpg",
    rotate: "rotate-right",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-6.jpg",
    rotate: "rotate-middle",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-8.jpg",
    rotate: "rotate-left",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-10.jpg",
    rotate: "rotate-right",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-11.jpg",
    rotate: "rotate-middle",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/5-15.jpg",
    rotate: "rotate-left",
    chapter: 5,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-10.jpg",
    rotate: "rotate-right",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-18.jpg",
    rotate: "rotate-middle",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-20.jpg",
    rotate: "rotate-left",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-25.jpg",
    rotate: "rotate-right",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-27.jpg",
    rotate: "rotate-middle",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-28.jpg",
    rotate: "rotate-left",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-30.jpg",
    rotate: "rotate-right",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/6-35.jpg",
    rotate: "rotate-middle",
    chapter: 6,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-1.jpg",
    rotate: "rotate-right",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-18.jpg",
    rotate: "rotate-middle",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-20.jpg",
    rotate: "rotate-left",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-22.jpg",
    rotate: "rotate-right",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-24.jpg",
    rotate: "rotate-middle",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-27.jpg",
    rotate: "rotate-left",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/7-28.jpg",
    rotate: "rotate-right",
    chapter: 7,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/9-1.jpg",
    rotate: "rotate-right",
    chapter: 9,
  },
  {
    title: "",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/pictures/15-1.jpg",
    rotate: "rotate-middle",
    chapter: 15,
  },
];

export default data;
