

const data = [
    {
    title: "Douglas with Grandma Lincoln",
    text: "Chapter 1, page 1",
    alt: "Douglas with Grandma Lincoln",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-1.jpg",
    rotate: "rotate-left",
    chapter: 1
  },
  {
      title: "Sisters giving approval to the 1st haircut",
      text: "Chapter 1, page 2",
      alt: "Sisters giving approval to the 1st haircut",
      sm: "auto",
      md: "auto",
      lg: "auto",
      color: "secondary",
      bordercolor: "dark",
      src: "/photos/1-2.jpg",
      rotate: "rotate-middle",
      chapter: 1
  },
  {
    title: "Me and Carolyn in my wagon",
    text: "Chapter 1, page 3",
    alt: "Me and Carolyn in my wagon",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-3.jpg",
    rotate: "rotate-right",
    chapter: 1
},
{
  title: "Our family outside the Log Church",
  text: "Chapter 1, page 4",
  alt: "Our family outside the Log Church",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-4.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "Siblings",
    text: "Chapter 1, page 5",
    alt: "Siblings",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-5.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "My preacher look",
  text: "Chapter 1, page 10",
  alt: "My preacher look",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-10.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Grandma Siggelkow with Glen and Gloria,  Grandma Lincoln with me and my sisters",
  text: "Chapter 1, page 11",
  alt: "Grandma Siggelkow with Glen and Gloria,  Grandma Lincoln with me and my sisters",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-11.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "Grandma Lincoln and me",
    text: "Chapter 1, page 12",
    alt: "Grandma Lincoln and me",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-12.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "My first dog, Spot",
  text: "Chapter 1, page 13",
  alt: "My first dog, Spot",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-13.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Uncle Jack Blizzard baptizing me",
  text: "Chapter 1, page 13",
  alt: "Uncle Jack Blizzard baptizing me",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-13-1.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "Thanksgiving Dinner with friends at Roundup",
    text: "Chapter 1, page 14",
    alt: "Thanksgiving Dinner with friends at Roundup",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-14.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "Christmas Dinner down on the farm with Grandpa and Grandma and Uncle Dave",
  text: "Chapter 1, page 16",
  alt: "Christmas Dinner down on the farm with Grandpa and Grandma and Uncle Dave",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-16.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "With cousins, Kathy and Pat, in Williams Lake",
  text: "Chapter 1, page 17",
  alt: "With cousins, Kathy and Pat, in Williams Lake",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-17.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "With Uncle Ralph's family in Williams Lake",
    text: "Chapter 1, page 17",
    alt: "With Uncle Ralph's family in Williams Lake",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-17-1.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "Grandma Lincoln and us",
  text: "Chapter 1, page 18",
  alt: "Grandma Lincoln and us",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-18.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Family photos with Grandma",
  text: "Chapter 1, page 19",
  alt: "Family photos with Grandma",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-19.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "Reading 'Dick & Jane' to Leslie",
    text: "Chapter 1, page 20",
    alt: "Reading 'Dick & Jane' to Leslie",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-20.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "A surprised Grandma Lincoln",
  text: "Chapter 1, page 21",
  alt: "A surprised Grandma Lincoln",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-21.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Dad's School bus gang",
  text: "Chapter 1, page 22",
  alt: "Dad's School bus gang",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-22.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "More family photos",
    text: "Chapter 1, page 23",
    alt: "More family photos",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-23.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "Performing at Pembina Bible Camp",
  text: "Chapter 1, page 24",
  alt: "Performing at Pembina Bible Camp",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-24.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Children's camp at Pembina",
  text: "Chapter 1, page 24",
  alt: "Children's camp at Pembina",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-24-1.jpg",
  rotate: "rotate-left",
  chapter: 1
},
{
    title: "Opening my Meccano set present Christmas 1954",
    text: "Chapter 1, page 26",
    alt: "Opening my Meccano set present Christmas 1954",
    sm: "auto",
    md: "auto",
    lg: "auto",
    color: "secondary",
    bordercolor: "dark",
    src: "/photos/1-26.jpg",
    rotate: "rotate-middle",
    chapter: 1
},
{
  title: "Outside the Church Dad built in Jarvie",
  text: "Chapter 1, page 27",
  alt: "Outside the Church Dad built in Jarvie",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/1-27.jpg",
  rotate: "rotate-right",
  chapter: 1
},
{
  title: "Our home in High River",
  text: "Chapter 2, page 1",
  alt: "Our home in High River",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-1.jpg",
  rotate: "rotate-right",
  chapter: 2
},
{
  title: "Our backyard with my VW bug",
  text: "Chapter 2, page 2",
  alt: "Our backyard with my VW bug",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-2.jpg",
  rotate: "rotate-middle",
  chapter: 2
},
{
  title: "This picture was taken shortly after we moved to High River",
  text: "Chapter 2, page 2",
  alt: "This picture was taken shortly after we moved to High River",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-2-1.jpg",
  rotate: "rotate-left",
  chapter: 2
},
{
  title: "About 1959",
  text: "Chapter 2, page 3",
  alt: "About 1959",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-3.jpg",
  rotate: "rotate-right",
  chapter: 2
},
{
  title: "After the bout with Rheumatic Fever",
  text: "Chapter 2, page 4",
  alt: "After the bout with Rheumatic Fever",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-4.jpg",
  rotate: "rotate-middle",
  chapter: 2
},
{
  title: "Barbie and Janice were the first foster children that stayed with us",
  text: "Chapter 2, page 5",
  alt: "Barbie and Janice were the first foster children that stayed with us",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-5.jpg",
  rotate: "rotate-left",
  chapter: 2
},
{
  title: "Christmas dinner with Dan and Danny Schnider",
  text: "Chapter 2, page 6",
  alt: "Christmas dinner with Dan and Danny Schnider",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-6.jpg",
  rotate: "rotate-right",
  chapter: 2
},
{
  title: "The last Christmas we had with Mom, Danny, Darla, Wayne, Gary, Mom, Henrietta, Aunt Annie and me",
  text: "Chapter 2, page 7",
  alt: "The last Christmas we had with Mom, Danny, Darla, Wayne, Gary, Mom, Henrietta, Aunt Annie and me",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-7.jpg",
  rotate: "rotate-middle",
  chapter: 2
},
{
  title: "Pal",
  text: "Chapter 2, page 8",
  alt: "Pal",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-8.jpg",
  rotate: "rotate-left",
  chapter: 2
},
{
  title: "Grandma and Sharon",
  text: "Chapter 2, page 9",
  alt: "Grandma and Sharon",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-9.jpg",
  rotate: "rotate-right",
  chapter: 2
},
{
  title: "Darla and Wayne's wedding",
  text: "Chapter 2, page 10",
  alt: "Darla and Wayne's wedding",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-10.jpg",
  rotate: "rotate-middle",
  chapter: 2
},
{
  title: "Leaving the Church",
  text: "Chapter 2, page 11",
  alt: "Leaving the Church",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-11.jpg",
  rotate: "rotate-left",
  chapter: 2
},
{
  title: "",
  text: "Chapter 2, page 15",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/2-15.jpg",
  rotate: "rotate-right",
  chapter: 2
},
{
  title: "",
  text: "Chapter 3, page 6",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/3-6.jpg",
  rotate: "rotate-right",
  chapter: 3
},
{
  title: "",
  text: "Chapter 3, page 12",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/3-12.jpg",
  rotate: "rotate-middle",
  chapter: 3
},
{
  title: "",
  text: "Chapter 3, page 15",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/3-15.jpg",
  rotate: "rotate-left",
  chapter: 3
},
{
  title: "",
  text: "Chapter 4, page 5",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-5.jpg",
  rotate: "rotate-right",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 9",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-9.jpg",
  rotate: "rotate-middle",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 11",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-11.jpg",
  rotate: "rotate-left",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 12",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-12.jpg",
  rotate: "rotate-right",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 15",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-15.jpg",
  rotate: "rotate-middle",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 18",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-18.jpg",
  rotate: "rotate-left",
  chapter: 4
},
{
  title: "",
  text: "Chapter 4, page 20",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/4-20.jpg",
  rotate: "rotate-right",
  chapter: 4
},
{
  title: "",
  text: "Chapter 5, page 5",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-5.jpg",
  rotate: "rotate-right",
  chapter: 5
},
{
  title: "",
  text: "Chapter 5, page 6",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-6.jpg",
  rotate: "rotate-middle",
  chapter: 5
},
{
  title: "",
  text: "Chapter 5, page 8",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-8.jpg",
  rotate: "rotate-left",
  chapter: 5
},
{
  title: "",
  text: "Chapter 5, page 10",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-10.jpg",
  rotate: "rotate-right",
  chapter: 5
},
{
  title: "",
  text: "Chapter 5, page 11",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-11.jpg",
  rotate: "rotate-middle",
  chapter: 5
},
{
  title: "",
  text: "Chapter 5, page 15",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/5-15.jpg",
  rotate: "rotate-left",
  chapter: 5
},
{
  title: "",
  text: "Chapter 6, page 10",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-10.jpg",
  rotate: "rotate-right",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 18",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-18.jpg",
  rotate: "rotate-middle",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 20",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-20.jpg",
  rotate: "rotate-left",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 25",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-25.jpg",
  rotate: "rotate-right",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 27",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-27.jpg",
  rotate: "rotate-middle",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 28",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-28.jpg",
  rotate: "rotate-left",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 30",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-30.jpg",
  rotate: "rotate-right",
  chapter: 6
},
{
  title: "",
  text: "Chapter 6, page 35",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/6-35.jpg",
  rotate: "rotate-middle",
  chapter: 6
},
{
  title: "",
  text: "Chapter 7, page 1",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-1.jpg",
  rotate: "rotate-right",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 18",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-18.jpg",
  rotate: "rotate-middle",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 20",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-20.jpg",
  rotate: "rotate-left",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 22",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-22.jpg",
  rotate: "rotate-right",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 24",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-24.jpg",
  rotate: "rotate-middle",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 27",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-27.jpg",
  rotate: "rotate-left",
  chapter: 7
},
{
  title: "",
  text: "Chapter 7, page 28",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/7-28.jpg",
  rotate: "rotate-right",
  chapter: 7
},
{
  title: "",
  text: "Chapter 9, page 1",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/9-1.jpg",
  rotate: "rotate-right",
  chapter: 9
},
{
  title: "",
  text: "Chapter 15, page 1",
  alt: "",
  sm: "auto",
  md: "auto",
  lg: "auto",
  color: "secondary",
  bordercolor: "dark",
  src: "/photos/15-1.jpg",
  rotate: "rotate-middle",
  chapter: 15
}
  ]

  export default data;